---
- name: checks if nginx is installed
  command: nginx -v
  register: nginx_installed
  ignore_errors: yes

- name: Add nginx repository
  apt_repository: repo=ppa:nginx/stable
  when: nginx_installed|failed

- name: Install nginx from package
  apt: name=nginx state=latest update_cache=yes
  when: nginx_installed|failed

- name: Remove the default app
  file: dest=/etc/nginx/sites-enabled/default state=absent

- name: Copy nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root group=root
  notify: 
    - restart nginx

- name: Ensure nginx is started
  service: name=nginx state=started enabled=true
  sudo: true